import { ClerkProvider, SignInButton, SignUpButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import './globals.css'
import { tjLocalization } from './others/location'

export const metadata = {
  title: 'Login Next Js',
  description: 'Generated by Next.js + Clerk',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      localization={tjLocalization} 
      appearance={{
        elements: {
          footer: { display: 'none' },
          formButtonPrimary: {
            backgroundColor: '#6c47ff',
            color: 'white',
            '&:hover': { backgroundColor: '#5a3be0' },
          }}}}>
      <html lang="en">
        <body>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedOut>
              <SignInButton>
                <button className="text-gray-600 font-medium">Ворид шудан</button>
              </SignInButton>
              <SignUpButton>
                <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5">Бақайдгирӣ</button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}